language: objective-c
python:
- '3.5.3'
before_install:
- brew unlink pyenv
- brew install fontconfig
- brew install pyenv
- export PYENV_ROOT=/usr/local/opt/pyenv
- eval "$(pyenv init -)"
- $SHELL -l
- env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.5.3
- pyenv local 3.5.3
- pyenv rehash
- python --version
- pip3 install -r requirements.txt
- pip3 install pyinstaller
- pyinstaller --onefile fms.py
- tar -zcvf dist/fms-darwin-x64.tar.gz dist/fms
- ls dist/
install: true
deploy:
  overwrite: true
  provider: releases
  skip_cleanup: true
  file:
  - dist/fms-darwin-x64.tar.gz
  on:
    tags: true
    all_branches: true
    repo: fontman/fms
  api-key:
    secure: QWxXKQpmVICz2yNPHjbZroYgQfbJEXR2F+fktj+mnwwZxflDBkoka8b9f+q5MvFWJm/B5V6HOUpZyUK+cHBmDqlbBCO5fyXNB5PV/NE2gmeWyUzwRiozsMQ7tYaXYaks/ISWMOaNN5mzShtgylaID9+gJu2Zfs9op3TM1VZu7wpVDgDgPpk4LEGP/AFE2qaLwZay+Jty41FegrD2aYUyYawFi/LkbVsLkKDnKq8DkcUrkM0b14ZtY4LSzXAK5xDOBPEsslPHcrf6c6HvAQqKEbFflOl2tKiG6f2Mvt32h4/eR6kmOQizitthebX0r0Z+dg2P6LRJ6O4tQQBY8RP5ebjA2veJG0TitG/dP9KZzx6SeeiAC5d9yN1l0DbY47RXejCI+7U22BHIoUyn9v+5KF03qjZVkIbPeRs3fgotTc90UyNqVq11LcrNJNWmok0gmCwK785PDY/3sKLFEJwdCTnB/kaSCHgwTZXNUc3hlV1MaP88gm7QFoOLkbkaHJNqex8RBhXGe6skhPxmb9pyAHMUCUI+NzpA7IzK/MBAblX57IzPt6SeNXokfGqGhspc1TNrMga6BMPha2phLmZaRit0bhOInsz1Nty7VJ1wqC9ox3KuILcwa5wNl6ecxIf7oqe6QXevBvD4XQ+4NNy1si/Cp1H8kYwti5MSq/vlMuo=
