language: objective-c
python:
- '3.5'
before_install:
- which python
- brew unlink python
- brew install python
- brew link --overwrite python
- brew install wget
- which python
- python --version
- pip install flask
- pip install requests
- pip install sqlalchemy
- pip install pyinstaller
- pyinstaller --onefile fms.py
- ls
- hdiutil create dist/fms.dmg -srcfolder dist/ -ov
- ls dist/
install: true
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: b02f9739adf601a764fa0457a270719b8bdb551d
  file:
    - "dist/fms.dmg"
  on:
    tags: true
    all_branches: true
    repo: fontman/fms